import { describe, expect, it } from "vitest";
import ExcelJS from "exceljs";
import { assertSafeXlsxArchive } from "../src/infrastructure/zipArchiveGuard.js";
import { ValidationError } from "../src/domain/errors/DomainErrors.js";

interface FakeEntry {
  name: string;
  compressed: number;
  uncompressed: number;
}

/** Minimal zip skeleton: local signature + central directory with the declared (possibly lying) sizes. Never decompressed. */
function fakeZip(entries: FakeEntry[]): Buffer {
  const local = Buffer.alloc(30);
  local.writeUInt32LE(0x04034b50, 0);
  const central = entries.map((e) => {
    const name = Buffer.from(e.name);
    const b = Buffer.alloc(46 + name.length);
    b.writeUInt32LE(0x02014b50, 0);
    b.writeUInt32LE(e.compressed, 20);
    b.writeUInt32LE(e.uncompressed, 24);
    b.writeUInt16LE(name.length, 28);
    name.copy(b, 46);
    return b;
  });
  const cd = Buffer.concat(central);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(cd.length, 12);
  eocd.writeUInt32LE(local.length, 16);
  return Buffer.concat([local, cd, eocd]);
}

const workbookEntry: FakeEntry = { name: "xl/workbook.xml", compressed: 100, uncompressed: 300 };
const MB = 1024 * 1024;

describe("assertSafeXlsxArchive", () => {
  it("accepts a real .xlsx generated by exceljs", async () => {
    const wb = new ExcelJS.Workbook();
    wb.addWorksheet("S").addRow(["process", "description"]);
    const buf = Buffer.from(await wb.xlsx.writeBuffer());
    expect(() => assertSafeXlsxArchive(buf)).not.toThrow();
  });

  it("rejects a non-zip file", () => {
    expect(() => assertSafeXlsxArchive(Buffer.from("process,description\nA,B\n".repeat(5)))).toThrow(ValidationError);
  });

  it("rejects an excessive declared total decompressed size", () => {
    const zip = fakeZip([workbookEntry, { name: "xl/a.xml", compressed: 20 * MB, uncompressed: 30 * MB }, { name: "xl/b.xml", compressed: 20 * MB, uncompressed: 30 * MB }]);
    expect(() => assertSafeXlsxArchive(zip)).toThrow(/decompressed size/);
  });

  it("rejects an entry with an excessive compression ratio", () => {
    const zip = fakeZip([workbookEntry, { name: "xl/sheets/sheet1.xml", compressed: 20_000, uncompressed: 20 * MB }]);
    expect(() => assertSafeXlsxArchive(zip)).toThrow(/compression ratio/);
  });

  it("rejects too many entries", () => {
    const zip = fakeZip([workbookEntry, ...Array.from({ length: 10_000 }, (_, i) => ({ name: `x/${i}`, compressed: 1, uncompressed: 1 }))]);
    expect(() => assertSafeXlsxArchive(zip)).toThrow(/too many entries/);
  });

  it("rejects vbaProject.bin (macros)", () => {
    const zip = fakeZip([workbookEntry, { name: "xl/vbaProject.bin", compressed: 100, uncompressed: 200 }]);
    expect(() => assertSafeXlsxArchive(zip)).toThrow(/macros/);
  });

  it("rejects an archive without xl/workbook.xml", () => {
    const zip = fakeZip([{ name: "word/document.xml", compressed: 100, uncompressed: 300 }]);
    expect(() => assertSafeXlsxArchive(zip)).toThrow(/workbook\.xml/);
  });

  it("rejects Zip64 sentinel values", () => {
    const zip = fakeZip([workbookEntry, { name: "xl/big.xml", compressed: 10, uncompressed: 0xffffffff }]);
    expect(() => assertSafeXlsxArchive(zip)).toThrow(/Zip64/);
  });
});
